# Generated by Django 4.1.7 on 2023-04-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='pet_name',
            field=models.CharField(max_length=30),
        ),
    ]
