# Generated by Django 4.1.7 on 2023-04-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_value',
            name='pet_type',
        ),
    ]
